# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricesCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('country', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProdcutDetials',
            fields=[
                ('productName', models.CharField(default='', max_length=120)),
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productDescription', models.CharField(default='', max_length=1200)),
                ('rating', models.CharField(default='', max_length=120)),
                ('thumbUrl', models.CharField(default='', max_length=240)),
                ('bigUrl', models.CharField(default='', max_length=240)),
                ('price', models.ManyToManyField(through='ecommerce.PriceSpecification', to='ecommerce.PricesCountry')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ProdcutDetials')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.FloatField(default=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ProdcutDetials')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specType', models.CharField(default='', max_length=200)),
                ('specValue', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=1900)),
                ('ratings', models.FloatField(default=2.5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ProdcutDetials')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('mobileNumber', models.IntegerField(default=96428)),
            ],
        ),
        migrations.AddField(
            model_name='userproductcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
        migrations.AddField(
            model_name='productspecifications',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SpecificationDetails'),
        ),
        migrations.AddField(
            model_name='prodcutdetials',
            name='specifications',
            field=models.ManyToManyField(through='ecommerce.ProductSpecifications', to='ecommerce.SpecificationDetails'),
        ),
        migrations.AddField(
            model_name='pricespecification',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ProdcutDetials'),
        ),
        migrations.AddField(
            model_name='pricespecification',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.PricesCountry'),
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set([('user', 'product')]),
        ),
    ]
